[build]
  command = "gatsby build"
  publish = "public/"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://keen-easley-6bcf04.netlify.com/*"
  to = "https://docs.dscjobs.org/:splat"
  status = 301
  force = true
